version: '3.8'
services:
  predictor:
    image: your-predictor-image:latest
    restart: always

  gateway:
    build:
      context: ./gateway/prod
    ports:
      - '80:80'
    depends_on:
      - predictor