services:
  predictor:
    build:
      context: ../predictor  # relatif terhadap folder gateway
    ports:
      - '5000:5000'

  gateway:
    build:
      context: ./dev      # folder dev di dalam gateway
    ports:
      - '3000:3000'
    depends_on:
      - predictor